//Auth Section
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_TYPE = {LOGIN: "LOGIN", REGISTER: "REGISTER"}
export const BUY = "BUY";
export const SELL = "SELL";
export const SEND = 'SEND';
export const CONVERSION_SUCCESS = "CONVERSION_SUCCESS";
export const CONVERSION_ERROR = "CONVERSION_ERROR";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_ERROR = "WITHDRAWAL_ERROR";

export default {
  LOGOUT,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGIN_CANCELLED,
  SAVE_TOKEN,
  DELETE_TOKEN,
  AUTH_REQUEST,
  AUTH_TYPE,
  BUY,
  SELL,
  SEND,
  CONVERSION_SUCCESS,
  CONVERSION_ERROR,
  WITHDRAWAL_SUCCESS,
  WITHDRAWAL_ERROR
};
